name: "Deploy Pull Request"
run-name: "Deploy Pull Request (${{ github.actor }})"

on:
  pull_request:
    types: [closed]
    paths:
      - 'force-app/**'
    branches:
      - develop
      - uat
      - master

jobs:
  PerformMetadataAnalysis:
    runs-on: ubuntu-latest
    name: "Perform Metadata Analysis"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      
      - name: "Initialize"
        uses: ./.github/actions/init

      - name: "Perform Code Analysis"
        uses: ./.github/actions/performCodeAnalysis
        with:
          failWhenViolations: false

      - name: "Perform Flows Analysis"
        uses: ./.github/actions/performFlowsAnalysis
        with:
          failWhenViolations: false

  DeployMetadata_Staging:
    if: ${{ github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true }}
    needs: PerformMetadataAnalysis
    runs-on: ubuntu-latest
    name: "Deploy Metadata (Staging/QA)"
    environment: "Staging"

    env:
      DEPLOYMENT_MODE: "deployWithTests"
      TARGET_DELTA_COMPARE_BRANCH: "HEAD~1"
      DELTA_DEPLOYMENT: true

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Initialize"
        uses: ./.github/actions/init

      - name: "Deploy"
        uses: ./.github/actions/deployMetadata
        with:
          targetOrgAuthUrl: ${{ secrets.ORG_AUTH_URL }}
          deploymentMode: ${{ env.DEPLOYMENT_MODE }}
          deltaDeployment: ${{ env.DELTA_DEPLOYMENT }}
          targetDeltaCompareBranch: ${{ env.TARGET_DELTA_COMPARE_BRANCH }}

  DeployMetadata_UAT:
    if: ${{ github.event.pull_request.base.ref == 'uat' && github.event.pull_request.merged == true }}
    needs: PerformMetadataAnalysis
    runs-on: ubuntu-latest
    name: "Deploy Metadata (UAT)"
    environment: "UAT"

    env:
      DEPLOYMENT_MODE: "deployOnly"
      TARGET_DELTA_COMPARE_BRANCH: "HEAD~1"
      DELTA_DEPLOYMENT: true

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Initialize"
        uses: ./.github/actions/init

      - name: "Deploy"
        uses: ./.github/actions/deployMetadata
        with:
          targetOrgAuthUrl: ${{ secrets.ORG_AUTH_URL }}
          deploymentMode: ${{ env.DEPLOYMENT_MODE }}
          deltaDeployment: ${{ env.DELTA_DEPLOYMENT }}
          targetDeltaCompareBranch: ${{ env.TARGET_DELTA_COMPARE_BRANCH }}

  DeployMetadata_Production:
    if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true }}
    needs: PerformMetadataAnalysis
    runs-on: ubuntu-latest
    name: "Deploy Metadata (Production)"
    environment: "Production"

    env:
      DEPLOYMENT_MODE: "deployWithTests"
      TARGET_DELTA_COMPARE_BRANCH: "HEAD~1"
      DELTA_DEPLOYMENT: true

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Initialize"
        uses: ./.github/actions/init

      - name: "Deploy"
        uses: ./.github/actions/deployMetadata
        with:
          targetOrgAuthUrl: ${{ secrets.ORG_AUTH_URL }}
          deploymentMode: ${{ env.DEPLOYMENT_MODE }}
          deltaDeployment: ${{ env.DELTA_DEPLOYMENT }}
          targetDeltaCompareBranch: ${{ env.TARGET_DELTA_COMPARE_BRANCH }}